format = """
$character $username $directory $custom 
"""

add_newline = false

[character]
format = "[$symbol](bold)"
success_symbol = "[󰊠 ](bold bg:# fg:#f2ae49)"
error_symbol = "[󰧵 ](bold bg:# fg:#de2a46)"

[username]
format = "[$user](bg:# fg:#d1d1d1 bold)"
disabled = false
show_always = true

[directory]
truncation_length = 100
truncate_to_repo = false
format = "[$path](fg:#8264DE bg:# bold)"

[custom.1]
command = 'echo "#"'
when = 'true'
format = '[$output](bg:# fg:#a0a0a0 bold)'

