format = """
$character$username$directory$custom 
"""

add_newline = false

[character]
format = "[](bg:# fg:#1a1a1a bold)[$symbol](bold)[](bg:#5040c9 fg:#1a1a1a bold)"
success_symbol = "[ 󰊠 ](bold bg:#1a1a1a fg:#f2ae49)"
error_symbol = "[ 󰧵 ](bold bg:#1a1a1a fg:#de2a46)"

[username]
format = "[ $user ](bg:#5040c9 fg:#d1d1d1 bold)[](bg:# fg:#5040c9 bold)"
disabled = false
show_always = true

[directory]
truncation_length = 100
truncate_to_repo = false
format = "[ $path ](fg:#5040c9 bg:# bold)"

[custom.1]
command = 'echo "\$_"'
when = 'true'
format = '[](bg:# fg:#1a1a1a bold)[ $output ](bg:#1a1a1a fg:#d1d1d1 bold)[](bg:# fg:#1a1a1a bold)'

