#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom --config ~/.config/picom/picom.conf -b &
wmname LG3D &
vmware-user
setxkbmap es
feh --bg-scale /usr/share/backgrounds/background.png &
~/.config/polybar/launch.sh &

bspc config pointer_modifier mod4

bspc monitor -d I II III IV V VI

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a '*:*:Picture-in-Picture' state=floating sticky=on

bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          40
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config single_monocle true
bspc config normal_border_color "#121212"
bspc config focused_border_color "#202020"

